### ISSUE TITLE
Where does tasks saves the information?

### ISSUE THREAD

**Issue by PortStone** [nextcloud/tasks#102]
Hey,

I just want to know the path of tasks data. So if someone has tasks where they save them.?

**Comment by raimund-schluessler** [comment]
The tasks are stored in the database by the caldav app of Nextcloud server. The table is called `*dbprefix*_calendarobjects`, the entries with `componenttype` VTODO are the tasks.

I would advise you not to mess with this table / the database in general on a productive system, unless you know what you are doing, since this may corrupt your data.
