### ISSUE TITLE
No alarm reminder

### ISSUE THREAD

**Issue by the-matzup** [nextcloud/tasks#1059]
There is no alarm (message, sound, etc.) for "end date" on terminal devices. At least not if the task was created by Nextcloud. Tasks created or modified by other applications (e.g. the app "Reminders" on the iPad) create a correct alarm entry, which then works. 

Since the entries with the alarm (or "end date") look identical on the Nextcloud web interface as well as on external applications, I took a look at the .ics entry and found that Nextcloud does not write an alarm (VALARM) into the task at all.

Created on Nextcloud:
`BEGIN:VTODO
UID:e038258f-4447-45bb-818d-8b3b745e2197
CREATED:20200524T132711
LAST-MODIFIED:20200524T132717
DTSTAMP:20200524T132717
SUMMARY:Test Nextcloud
DUE:20200524T150000
END:VTODO
END:VCALENDAR`

Created on the iPad
`BEGIN:VTODO
CREATED:20200524T112532Z
DTSTAMP:20200524T112543Z
DTSTART;TZID=Europe/Berlin:20200524T140000
DUE;TZID=Europe/Berlin:20200524T140000
LAST-MODIFIED:20200524T112543Z
STATUS:NEEDS-ACTION
SUMMARY:Test ipad
UID:4680CB65-E38A-4881-8085-A7C52F0509C9
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Reminder
TRIGGER;VALUE=DATE-TIME:20200524T120000Z
UID:92B8DB7A-ECCF-41BF-ABBB-234A58CA8B02
X-WR-ALARMUID:92B8DB7A-ECCF-41BF-ABBB-234A58CA8B02
END:VALARM
END:VTODO`

---

Both entries look identical. One entry was created with Nextcloud, the other entry with iPad. One reminder/alarm works, the other does not.

Nextcloud:
![Bildschirmfoto 2020-05-24 um 13 35 49](https://user-images.githubusercontent.com/47818886/82753956-1d5fe580-9dca-11ea-90ef-5c146d09674e.png)

iPad:
![IMG_761F9D7CCEB9-1](https://user-images.githubusercontent.com/47818886/82753958-251f8a00-9dca-11ea-822b-6b0c19887a09.jpeg)

---
NC 18.0.4
Task 0.13.1

**Comment by raimund-schluessler** [comment]
Well, the due date and the reminder/alarm (date) are not the same thing. A task can be due at a certain time and not have an alarm. And even though Apple seems to create an alarm when you set a due date, as a user I would find it very weird if an alarm was automatically created when I set a due date.

That being said, Nextcloud Tasks does not support creating alarms yet. The corresponding issue is https://github.com/nextcloud/tasks/issues/154.

**Comment by serranomorante** [comment]
Hi. I have an alternate solution for this.

First, on desktop I use **Thunderbird** as a desktop client, but you can still use the Nextcloud Tasks GUI and this solution will still work.
Then on iPhone I use the **Reminders** app as the mobile client.

When you create a new task from desktop, even thought the task gets successfully synced and appears on the **Reminders** app as it should, an alarm would NOT be automatically created because the **Reminders** app only creates an alarm if you add that new task from within the app itself.

The solution is very simple, you just need to force **Reminders** app to "update" that task (you can update any field you want) and and at that moment the alarm would be automatically created for that task.

**Don't worry**, you don't need to go task by task in the **Reminders** app making an "update" so the alarm is automatically created. You could just create an **iOS Shortcut + Automation** to do that for you automatically whenever you open and close the **Reminders** app.

When you open the **Reminders** app, your tasks would be synced.
When you close the **Reminders** app, the **iOS shortcut** would run, automatically adding alarms to all those tasks that don't have one.

Sorry If I don't share the full explanation to create the **iOS shortcut** and the **Automation** but here are some screenshots:

**iOS shortcut**

![iOS shortcut](https://i.postimg.cc/Yq21G13b/IMG-7680.jpg)

**Automation**

![Automation](https://i.postimg.cc/hjMkSLsN/IMG-7679.jpg)

This is all you need.

**Comment by bhavin07** [comment]
> Hi. I have an alternate solution for this.
> 
> First, on desktop I use **Thunderbird** as a desktop client, but you can still use the Nextcloud Tasks GUI and this solution will still work. Then on iPhone I use the **Reminders** app as the mobile client.
> 
> When you create a new task from desktop, even thought the task gets successfully synced and appears on the **Reminders** app as it should, an alarm would NOT be automatically created because the **Reminders** app only creates an alarm if you add that new task from within the app itself.
> 
> The solution is very simple, you just need to force **Reminders** app to "update" that task (you can update any field you want) and and at that moment the alarm would be automatically created for that task.
> 
> **Don't worry**, you don't need to go task by task in the **Reminders** app making an "update" so the alarm is automatically created. You could just create an **iOS Shortcut + Automation** to do that for you automatically whenever you open and close the **Reminders** app.
> 
> When you open the **Reminders** app, your tasks would be synced. When you close the **Reminders** app, the **iOS shortcut** would run, automatically adding alarms to all those tasks that don't have one.
> 
> Sorry If I don't share the full explanation to create the **iOS shortcut** and the **Automation** but here are some screenshots:
> 
> **iOS shortcut**
> 
> ![iOS shortcut](https://camo.githubusercontent.com/2b7a77a1f93353fa0f32f34f84acb34addbfbfe8d95a5395cbb23f672014cabd/68747470733a2f2f692e706f7374696d672e63632f59713231473133622f494d472d373638302e6a7067)
> 
> **Automation**
> 
> ![Automation](https://camo.githubusercontent.com/23d92cf82762ee9d7a2e555bb004027b00470cd0e0c709c218b32311673e0358/68747470733a2f2f692e706f7374696d672e63632f686a4d6b534c734e2f494d472d373637392e6a7067)
> 
> This is all you need.

Hi @serranomorante ,

Thank you for sharing the idea on the shortcut.

In the shortcut, I wasn't able to find an action that "Sets the alarm" on the task.

Would you be kind enough to share the complete solution, please?
