### ISSUE TITLE
Store tasks as TODO.txt?

### ISSUE THREAD

**Issue by PopeRigby** [nextcloud/tasks#1077]
This is just an idea. Would it be possible to store your tasks in your files as a TODO.txt, so you could use any TODO.txt compatible application to manage your Nextcloud tasks?

**Comment by raimund-schluessler** [comment]
I don't think this is practical. You would need to keep the CalDAV database in sync with the todo.txt files. Not only would you have a bazillion text files then (possibly one for each todo ever created), but also parsing such an edited todo text file would be a nightmare (e.g. what happens when the text file is not valid, because you used the wrong syntax?). Importing ICS files correctly is often giving errors already, and these files mostly are exported automatically. Importing manually edited files won't go well.

Overall, this is nothing I would like to implement, sorry.

**Comment by PopeRigby** [comment]
Fair enough.
