### ISSUE TITLE
 Dropdown menu on complete task is unclickable, Hard to read

### ISSUE THREAD

**Issue by NukeManDan** [nextcloud/tasks#1146]
### Steps to reproduce
1. Complete a task. (click checkbox)
2. Go to completed tasks
3. Expand dropdown menu on item
4. attemt to click item in menu
5. clicks task item below menu
 
### Expected behaviour
I can click on dropdown menu items, and read them. Opacity here is an issue. Especially in dark mode.

### Actual behaviour
hard to read all content in completed section, can't click UNLESS a task item is not underneath it.
![image](https://user-images.githubusercontent.com/35669742/88603365-ed36fc00-d031-11ea-9770-a29098176dc2.png)

**Comment by raimund-schluessler** [comment]
Coincidentally this has been fixed with the task list design update #1136:

![Screenshot_2020-07-28 Aufgaben - Nextcloud](https://user-images.githubusercontent.com/2496460/88630013-4a719280-d0b0-11ea-8b11-0155aef2d47d.png)

![Screenshot_2020-07-28 Aufgaben - Nextcloud(1)](https://user-images.githubusercontent.com/2496460/88630166-7e4cb800-d0b0-11ea-8803-51bdff06d071.png)
