### ISSUE TITLE
Subtasks are transferred (from DAVdroid) as a comment in nextcloud task app?

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/tasks#116]
I use davDroid to sync tasks with my phone

When i have subtasks in the android tasks app they are transfered to nextcloud as comments 
like this

[ ] Autorização LNEC
[x] Certificado PhD
[x] Registo criminal
[x] Cópia cc
[x] Segurança social voluntária
[x] Formulários
[x] IBAN

why?

Since nextcloud tasks app also have the ability to do sub-tasks, i was expecting to see those sub-tasks (that are in my phone) also as subtasks in nextcloud.

Is it really like this?

thanks

**Comment by raimund-schluessler** [comment]
This is due to DAVdroid. It doesn't really store the subtasks as own tasks, but utilizes the notes field to emulate some kind of subtasks behavior. We cannot do anything against this here, neither in the app nor on the server side.

The only improvement we can do is to support markdown in the notes field: https://github.com/nextcloud/tasks/issues/76

**Comment by Ricardosgeral** [comment]
ok. maybe DavDroid guys to implement this! I will ask then!
thanks

**Comment by varac** [comment]
@Ricardosgeral Did you create a feature request for DavDroid ? If so, can you share the URL pls ?

Btw, [markdown support in the description field](https://github.com/nextcloud/tasks/issues/76) got implemented already.

**Comment by varac** [comment]
This is the related subtask issue for the android "tasks" app: https://github.com/dmfs/opentasks/issues/37
