### ISSUE TITLE
[Feature Request] Priority number and +/- buttons in the tasks list

### ISSUE THREAD

**Issue by bgravato** [nextcloud/tasks#1166]
Clicking on the star icon (priority) in the task list toggles between priorities 1 (highest) and 0 (not assigned).

It would be great if there was instead a '+' and a '-' signs (or up/down arrows) in order to increase/decrease priority of the tasks without having to click/open the task and use the slider.

It would also be great to have the priority number written over the star, so one could easily distinguish between the different priorities that have the same colour (eg. 1-4 and 6-9).

Thanks for this great app!

**Comment by raimund-schluessler** [comment]
We will definitely not put plus and minus buttons on the task items in the task list. We just recently moved most action buttons into a dropdown menu to clean up the interface. Adding two new buttons would contradict this effort.

That being said, we have another request to reduce the amount of priority values to 4 in https://github.com/nextcloud/tasks/issues/1128. In case we do that, showing a number for the priority would not be needed anymore, since the colors would be enough then. I would like to hear the opinion of @Torenga here, because he created #1128 and liked #1166, which seems contradictory to me 😉.

And instead of the showing plus/minus buttons, we could simply show a button for each priority value (this would be possible with 9 priority values already, but would lead to many buttons).

Let's please move the discussion how to improve priority settings to #1128. I will adjust the title accordingly to reflect the more general discussion.
