### ISSUE TITLE
connection tasks to calender app

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/tasks#13]
### Steps to reproduce
1.copy link form a list
2.goto calender app on webinterface
3.add link to "new subscription"

### Expected behaviour
Tell us what should happen
Could not integrate tasks via CalDav link to Calender app
Error message: The remote server did not give us access to the calendar (HTTP {401} error)

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Docker Container: indiehosters/nextcloud:10.0.1

**Database:**
mysql (docker) version 5.7

**PHP version:**
fpm-5.6

### Client configuration
**Browser:**
firefox 50

**Comment by raimund-schluessler** [comment]
I am not sure, what you try to achieve here. It makes no sense to subscripe to a calendar which is basically already present.

My guess is that you want to see a "Task list" as a calendar in the Calendar app. It is by design that they do not show up in the calendar app to not spam the calendar list. If you want a calendar which accepts both tasks and events, create it in the Calendar app. It will also show up in the Tasks app.

**Comment by raimund-schluessler** [comment]
@georgehrke Maybe you are interested in what happens when you try to subscribe to a calendar which is actually your own.

**Comment by stephanfriedrich** [comment]
@raimund-schluessler 
i cant figure out, how i connect my specific todo with my calender.
i allready create a sperate calender called "todo", and connect some tasks in within the task-app to this todo-calender. but i cant see any tasks im my calender app?!
