### ISSUE TITLE
[Feature Request] Share task lists

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/tasks#14]
Hi, 

will there be any futhur plan to add a share function, to share task lists with other users?

**Comment by raimund-schluessler** [comment]
Yes, but I cannot give any timeline.

**Comment by enboig** [comment]
readme.md says "Tasks can be shared between users."; but I cannot see how.

**Comment by LollenJumplan** [comment]
Well, you can kinda do it because task lists are implemented as calendars. You need to create your tasklist/calendar from the calendar app though, and share that, and now multiple users can edit the task list.
If you create it from the tasks app, the list will be hidden in calendar as far as I can see so you can't really share it then.

**Comment by raimund-schluessler** [comment]
> Well, you can kinda do it because task lists are implemented as calendars. You need to create your tasklist/calendar from the calendar app though, and share that, and now multiple users can edit the task list.
If you create it from the tasks app, the list will be hidden in calendar as far as I can see so you can't really share it then.

This is the only option right now.

**Comment by yvesle** [comment]
Hi 

 I tried the method explained but it does not work for editing. The other user can see the tasks but cannot edit them.
Odly enough I have two "share" tick box on the shared calendar after I try to access the task with the second user. Ticking the tickbox one on the first line does not stick. If I go to the file section and back, it shows as unticked again.
If I delete it, try again to modify with the second user and comes back, I have again the two lines.
![image](https://user-images.githubusercontent.com/22190569/31446142-183434ba-aea0-11e7-85de-37c9ec7d6007.png)

Using latest stable nextcloud 12.0.3 and plugin task 0.9.5
Any idea on what could be done ?

Otherwise great job overall
Regards

**Comment by SehLax** [comment]
> I tried the method explained but it does not work for editing. The other user can see the tasks but cannot edit them.
for me it works both with single users and groups. creating a calendar in the calendar app, sharing it in the calendar app (checking "can edit"), and adding tasks in the task app → other users can see AND edit the tasks

**Comment by GoetheG** [comment]
Hi there,

great that this is more clear now. Is there a chance to make all this calendar and task stuff a little bit easier for the users? It all seems rather complicated for users who aren't tech specialists. Looking forward to a little bit more intuitive user experience.

We are currently using Open-XChange for calendar and tasks but I hope that we'll move to Nextcloud some day. But at this point there are only limited options to access user rights. It's important to me that only a seleced group of people can read and/or edit tasks.

Thank you people :)

**Comment by JohnWalkerx** [comment]
Does anybody know if someone works on this Feature Request?
I think the UX will be much better for normal users.
