### ISSUE TITLE
recurring tasks allways reappear (regression)

### ISSUE THREAD

**Issue by h1618** [nextcloud/tasks#1402]
### Steps to reproduce

1. Create an recurring task in thunderbird
2. mark one recurrence finished
3. see it reappear as not finished when next synced

### Expected behaviour

past recurrences should keep their finished date and state

### Actual behaviour

past tasks reappear with finished state 0%

### Server configuration

**Operating system**: Debian buster (Armbian) / Linux 5.10.4-sunxi

**Web server:** nginx 1.14.2-2+deb10u3

**Database:** mariadb-server-10.3 10.3.27-0+deb10u1

**PHP version:** 7.4 7.4.13-1+0~20201130.33+debian10~1

**Nextcloud version:** (see Nextcloud admin page) 20.0.5

**Tasks version:** (see Nextcloud apps page) 0.13.6

**Updated from an older Nextcloud or fresh install:** updated since nextcloud 10 or so

This did work in previous versions, but since some time all recurring tasks are not working correctly - finished state not kept.

**Comment by raimund-schluessler** [comment]
Did you interact with the Tasks app (and specifically with the recurring task) between the syncs? I ask, because the Tasks app is just a client and doesn't handle, despite edit any task without user interaction.

So if you don't open the Tasks app, it cannot be the reason for the problem. It would be great if you could check this (best would be to disable the Tasks app and check syncing recurring Tasks with Thunderbird).

That being said, the Tasks app does not and never did support recurring Tasks, see https://github.com/nextcloud/tasks/issues/34 and specifically https://github.com/nextcloud/tasks/issues/316 for Thunderbird.

And if it really did work in the past (and you can exclude the Tasks app from interfering) this is most likely a server issue.

**Comment by firta4** [comment]
I have the same issue with my recurring tasks from Thunderbird since I updated from NC19 to NC20. It occurs even when the Tasks app is deactivated.
I think it is safe to assume that it is a server issue, like @raimund-schluessler said.

**Comment by dseomn** [comment]
I just filed https://github.com/nextcloud/server/issues/25394 in the server based on @raimund-schluessler's comment.

**Comment by mlegner** [comment]
To help others who also experience(d) this issue: It turned out to be a [bug in Thunderbird](https://bugzilla.mozilla.org/show_bug.cgi?id=1686466) that has apparently been fixed in Thunderbird 78.8. I believe this issue here can be closed.

**Comment by raimund-schluessler** [comment]
Ok, then I will close this issue.
