### ISSUE TITLE
Activity log showing endless loop of updates when no updates are made

### ISSUE THREAD

**Issue by c-prompt** [nextcloud/tasks#1419]
We have multiple PCs using Thunderbird for tasks and multiple Androids using Tasks. We're seeing activity for the same tasks over and over even though no updates have been made. Except where I wrote "Task activity OK" on the image, you can see that NextCloud thinks I updated a task, only to have another person update the task, after which I update it again, and then the other person... and so on. I've seen this for many months on various tasks but can't determine what could be causing an update. Any thoughts how to troubleshoot? One possible reason is there's a bug related to Thunderbird snoozing a task (e.g., someone snoozes the task on Thunderbird, which resets someone else's Thunderbird snooze, which resets the original person...).

![Activity list - repeating tasks](https://user-images.githubusercontent.com/10625352/107820865-253d2c80-6d41-11eb-9b14-ff8ba8653e9d.png)

NextCloud 20.0.7
Tasks 0.13.6
Activity 2.13.4
OS Linux 4.19.0-14-amd64 x86_64
PHP 7.3.27
MySQL 10.3.27

**Comment by raimund-schluessler** [comment]
I think this question is better suited for the forum, since this is very likely not a bug in Tasks.

And I am sorry to say that I don't have an idea what could cause this. But to make sure that Tasks is not involved in it, please disable the Tasks app and monitor the activity log. The CalDAV sync with your devices is handled by the Nextcloud server, Tasks is only a client and causes no background requests without user interaction.
