### ISSUE TITLE
[Feature Request] Exporting and Importing groups of tasks

### ISSUE THREAD

**Issue by Eric-Sparks** [nextcloud/tasks#1467]
I'd like the ability to create a bunch of tasks and export them (or otherwise save them for later).  And then, when needed, take those saved tasks and drop them into the task app and have them processed as usual.

This would be good for unscheduled, recurring events like product releases, disaster and emergency responses, and anything else that a checklist would be good for, only now you're able to take this and very simply assign out the different tasks to other people very quickly and have those tasks show up on their lists and you can still track everything.

**Comment by raimund-schluessler** [comment]
You can already export a complete task list as ICS file. Importing tasks is currently not possible from within the Tasks app, see https://github.com/nextcloud/tasks/issues/122 for the corresponding issue. However, if the task lists supports calendar entries, it shows up in the Calendar app and you can import tasks there as a work-around.

I think exporting only selected tasks is a bit to specific. As said, you can export a complete calendar. In case it contains tasks you don't want to import again, you could simply remove them from the ICS with the text editor of your choice.

That being said, the only problem is that Tasks does not support importing data. Since this is tracked in #122 already, I will close this issue.
