### ISSUE TITLE
Do not create a calendar when creating a task list

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/tasks#1608]
On Tasks 13.6 (NC21.0.2) when creating a new task list, the list is created as expected. But it automatically also creates a new calendar with the same name in the Calendar app. This is unexpected and should not be the case. Plus, when the calendar is deleted, this also deletes the corresponding task list, which is also unexpected.

Since recently, it is possible to create calendars in the Calendar app *without* also creating task lists in the Tasks app, so I wonder whether it is also possible to only have task lists created without a calendar.

I am aware that both calendar and task list are CalDAV resources, but it should be possible to disconnect these and have separate resources for the Calendar app and the Tasks app in the CalDAV server.

Rationale: auto-created calendars are empty, but clutter the calendar list view on all devices that are connected to that Nextcloud account. This is especially annoying with lists which are shared among users, e.g. project-related todo lists, because they also auto-share their corresponding calendars.

**Comment by szaimen** [comment]
> when creating a new task list, the list is created as expected. But it automatically also creates a new calendar with the same name in the Calendar app.

It only does that if in the calendar app the option to show tasks lists in the calendar view is activated. You can hide them by disabling this setting in the calendar app. => No bug => closing

**Comment by raimund-schluessler** [comment]
@szaimen is correct. By default, the Tasks app creates lists/calendars which can only contain `VTODO`s, see here https://github.com/nextcloud/tasks/blob/master/src/store/calendars.js#L498 (only the `VTODO` component is set for the list). This is the behaviour you expect.

However, the Calendar app has the option to show tasks with a due date in the calendar view. If this is enabled, the Calendar app also considers calendars which can only contain `VTODO`s (otherwise it couldn't show the tasks in these calendars). If you disable this option, such calendars/lists are not shown in the Calendar app anymore.

**Comment by mcnesium** [comment]
thank you for the kind explanation, sorry for not rtfm… :roll_eyes:
