### ISSUE TITLE
Compatible Android Apps

### ISSUE THREAD

**Issue by c0fe** [nextcloud/tasks#173]
Is there a list of compatible android apps with this? I have this app installed in my Nextcloud instance and yet no client can sync up with the Tasks app.

**Comment by raimund-schluessler** [comment]
I find this question a bit weird, because the Tasks app is only a client itself. It does not provide any service to other clients. It just shows and manipulates the VTODOs on the Nextcloud server following the CalDAV standard.

So, you need to find an app which is able to connect to a CalDAV server and show the VTODOs (aka tasks). As I don't own an Android phone, I am no big help here, but I guess, that this app http://tasks.org/ could do. On iOS this feature is build in.
