### ISSUE TITLE
Storage location

### ISSUE THREAD

**Issue by FelixSimonMertins** [nextcloud/tasks#1900]
Hey, so i would like to know, where exactly is all data stored... i couldn't find any new database entry...

**Comment by FelixSimonMertins** [comment]
Edit: I have found out, that those are stored in the calendar object props table in the databse... However, i am looking for the location of the task progress, since i wanna be able to sync that with an webpage for our customers to view their order progress...

**Comment by raimund-schluessler** [comment]
Well, you found it. It is in this table, but there is no separate column for the progress. You will need to parse the ics data blob, effectively making your app a CalDAV client. Not sure if just showing the progress is worth the effort.
And if you decide to do it, I would advice to not directly read the table, but go through the CalDAV interface.

If you have further questions, please ask them in the forum. Your problem is not related to the Tasks app (which is just a CalDAV client itself and does not handle storing data in the database).
