### ISSUE TITLE
Show "Calendar will be deleted" clearly in the UI

### ISSUE THREAD

**Issue by hardfire** [nextcloud/tasks#196]
### Steps to reproduce
1. Click on three dots
2. Click on delete
3. Click on the trash icon

### Expected behaviour
The delete interface should clearly mention that the calendar would also be deleted. 

### Actual behaviour
The app shows a popover only after the countdown starts. I realized there was a message only after clicking on the trash icon and it was too late by the time i realized it. 

I don't remember all that i had in my calendar, so now i am not sure if i lost something important or now. I think the UI should be more clear and not just a popup in the case of deletion, especially because i just installed the tasks app to test and I saw there was a "Personal" task list. I didn't realize it came from my calendar which is also named Personal. Only after it was too late :(

**Comment by raimund-schluessler** [comment]
@hardfire So do I understand it correctly, that the confusion is about that also the events in the calendar will be deleted and not only the tasks? What would be your suggestion to make this more clear?

To improve that, we could:
- Change the text in the tooltip from `This will delete the Calendar xyz and all of its entries.` to `'This will delete the Calendar xyz and all corresponding events and tasks.`
- Show the tooltip permanently and not only on hover. This would maybe give more time to actually read it.

@hardfire What dou you think?

Anyway, in the end this will all be a lot better once we have the undo option for calendars, see https://github.com/nextcloud/calendar/issues/12, https://github.com/nextcloud/calendar/issues/13 and also https://github.com/nextcloud/server/issues/3216.

Also, please consider doing a backup of your database regularly. This is recommended anyway in case of hardware failure or other havoc and would safe you after accidental data deletion.

@skjnldsv as well, because we talked about the confirmation prompt recently.

**Comment by skjnldsv** [comment]
@raimund-schluessler Yes, changing the message could be enough for now I guess :)

**Comment by hardfire** [comment]
@raimund-schluessler yes! that's correct. In my case, showing the tooltip permanently would have helped.

**Comment by hardfire** [comment]
Pretty cool! thank you so much for the quick response and fix! :D love this.
