### ISSUE TITLE
task listed in current tab if subtasks start date not set

### ISSUE THREAD

**Issue by claudius-kienle** [nextcloud/tasks#1984]
### Steps to reproduce
1. Add task, set start date to some date in the future
2. Add a subtask to that task without adding a start date to the subtask

### Expected behaviour
The task and all of it's subtasks should not be visible in the _Current_ tab, since the task's start date is set to some date in the future. Therefore, if the tasks start date is set, it should ignore the subtasks start date to check if it should be listed in the current tab.

### Actual behaviour
The task will be visible in the _Current_ tab while one of its subtasks has a start date not set to the future.

**Comment by raimund-schluessler** [comment]
This is by design. It works like this for other parameters of subtasks as well, like priority  or due date. If a task or subtask matches a list, we have to show it's ancestor tasks as well, otherwise the subtask would not be visible in the appropriate list. If a subtask has a high priority, we show it in the "Important" list, even if its parent task has no priority set. The same logic applies to current tasks. If a subtask is current, i.e. start date in the past or no start date, we show it and its parent in the "Current" list.
