### ISSUE TITLE
Tasks JSON API

### ISSUE THREAD

**Issue by memen45** [nextcloud/tasks#2003]
Is it possible to access tasks through an API that can return JSON responses? I have an idea to create an integration on wearable devices, but the devices cannot parse XML. The most direct way to access the tasks would be through the CALDAV interface immediately, however, as far as I know, this only returns XML documents.

Do you see any possibility to obtain JSON formatted tasks from Nextcloud?

**Comment by raimund-schluessler** [comment]
Please see https://github.com/nextcloud/tasks/issues/304.

There is no API in Nextcloud server to get tasks as JSON object. The Tasks app itself is a CalDAV client, so it communicates with the server via its CalDAV interface. If you really need a JSON API to get tasks, you could create one on the server side (using PHP) and distribute it as a standalone app.

Since this is out of scope for the Tasks app in my opinion, this is nothing that we will implement here.

**Comment by memen45** [comment]
Thanks for your response! I see now that the CalDAV implementation is outside of the scope for this repo. 

For future readers/reference: I actually found a way to at least obtain calendars (including tasks) in JSON format from the current CalDAV backend [here](https://help.nextcloud.com/t/get-calendar-events-as-json/46539).
