### ISSUE TITLE
[Feature Request] Is there any possibility that a task/card becomes non-editable after creation

### ISSUE THREAD

**Issue by intelligi123** [nextcloud/tasks#2074]
Hi

I am deploying tasks in my organization where employees are able to add tasks to their dashboard and add details along with tentative deadlines. Employees themselves have the responsibility of task creation as its best for adding subtasks and current progress.

However I am interested if there is a way that dates/tasks entered by the employees become non-editable for them after creation. I mean how can I restrict their privileges of modifying their tasks.

Is there already a feature or I need to make modifications in any way?

Thank you so much.
Regards

**Comment by raimund-schluessler** [comment]
As far as I am aware, there is no such thing as per entry/event/task access permissions in CalDAV, especially not on a per-parameter basis. And I think it would be counter-intuitive if not frustrating if a user is not allowed to edit entries in their own calendar anymore.

What *might* work for you (not sure, since I don't understand your use-case enough, I guess), would be to create a calendar as admin, share it with your users as not-allowed-to-edit, and move every task that should be read-only into this calendar after it was created.
