### ISSUE TITLE
Feature Request: Auto-delete completed tasks

### ISSUE THREAD

**Issue by kvibber** [nextcloud/tasks#2125]
I like to clear out old tasks over time, so I don't have 50 completed tasks that just say "Groceries" or something like that. I know I can display completed tasks per list and delete them that way, but it would be convenient to auto-delete any tasks that have been completed after a certain amount of time.

**Comment by raimund-schluessler** [comment]
I am not so convinced of this feature, since it might lead to data loss if used without care and does not seem to create a lot of benefit, given that you can already delete all completed tasks of a list with two clicks.

Also, the Tasks app only works on the client side. So a planned deletion would only work when the Tasks app is loaded/used, which does not seem ideal to me, as it might be seen as a bug by users.

So if this feature is to be implemented, it needs to be done on the server side. So please open an issue for this in the [server repository](https://github.com/nextcloud/server).

**Comment by JustACasual** [comment]
I was just searching for this exact feature, and I would love it.
Currently, I just don't display done tasks, but this means in the background, done tasks are piling up.
Also, I would love to display done tasks, which were closed during the last 24 hours, just to see some progress in my list :)

**Comment by yogo1212** [comment]
@raimund-schluessler could you provide one or two pointers for implementing automatic deletion?
i'm also using the tasks app to organise and share my shopping list. it's very practical for organising items into sub-lists and my wife being able to add more items from home but over longer periods of use, the app becomes very sluggish with all the tasks (and subtasks) accumulating in the background.
