### ISSUE TITLE
Task not supported on IOS Nextcloud App

### ISSUE THREAD

**Issue by CoolJoni** [nextcloud/tasks#213]
Please add the support for the IOS App

**Comment by raimund-schluessler** [comment]
iOS natively supports the CalDAV protocol, see here for how to set it up: https://docs.nextcloud.com/server/14/user_manual/pim/sync_ios.html. After setting the CalDAV sync up, you can access tasks (and calendars entries) with the native iOS apps. Hence, the Nextcloud iOS app will not have support for accessing tasks, because the native iOS apps are the better solution. Anyway, there is an issue for setting up the CalDAV sync by the iOS app: https://github.com/nextcloud/ios/issues/70. Please also report all issues related to the iOS app in this repository.
