### ISSUE TITLE
Support markdown.

### ISSUE THREAD

**Issue by rokejulianlockhart** [nextcloud/tasks#2191]
Tasks.org supports it, so when my tasks synchronize, they are significantly less legible from the Nextcloud Tasks interface.

Supersedes https://github.com/nextcloud/tasks/issues/1486.

**Comment by raimund-schluessler** [comment]
Tasks has markdown support in the notes field.

**Comment by beedell-roke** [comment]
> The rest is tracked in the issue you mentioned.

@raimund-schluessler, is `webo.cloud` perhaps using an old version, then?

<p></p>

<img width="1279" height="719" alt="Image" src="https://github.com/user-attachments/assets/c4642392-40bd-48b4-b580-7f60f48d1ed7" />

<p></p>

They were one of the suggested partners at the official “Join Nextcloud” webpage, when I registered…

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler, is webo.cloud perhaps using an old version, then?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/42837531/217106667-7feb9331-21d0-4820-aca7-d307f4744c80.png)
> 
> 
> 
> They were one of the suggested partners at the official join-nextcloud webpage when i registered...

I don't know which version they use. Latest version is 0.14.5. 

How does the note field look when you type markdown in it?

**Comment by beedell-roke** [comment]
> How does the note field look, when you type Markdown in it?

@raimund-schluessler, apologies for missing your response. I've renamed this issue, [^2] so that its scope is more obviously what the original issue content describes [^3] — support for Markdown *in task titles*. [^1]

[^3]: [`#issue-1570770504`](https://github.com/nextcloud/tasks/issues/2191#issue-1570770504)

[^2]: [`#event-15573376910`](https://github.com/nextcloud/tasks/issues/2191#event-15573376910)

[^1]: [`gitlab.com/gitlab-org/gitlab/-/issues/577274`](https://gitlab.com/gitlab-org/gitlab/-/issues/577274)

**Comment by beedell-roke** [comment]
> [`#issuecomment-2526189903`](https://github.com/nextcloud/tasks/issues/2191#issuecomment-2526189903)

@raimund-schluessler, please re-triage this as a duplicate of [`issues/2973`](https://github.com/nextcloud/tasks/issues/2973#issue-3571367158). [^1]

[^1]: [`#event-3769657806`](https://github.com/nextcloud/tasks/issues/2191#event-3769657806)
