### ISSUE TITLE
Images and HTML tags not rendered in Notes section of tasks.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [nextcloud/tasks#2274]
### Steps to reproduce

1.	Create a task with

	```markdown
	# https://github.com/webcompat/web-bugs/issues/120964#issuecomment-1518197248
	
	<blockquote>
	
	@softvision-raul-bucata, cookies were accepted if prompted.
	
	![image](https://user-images.githubusercontent.com/42837531/233709552-92ef1107-acab-4a14-bf01-653ba66be00d.png)
	
	I just tried `firefox --safe-mode`, though, and login worked, so I'll find the actual culprit myself. Thanks.
	
	</blockquote>
	```

	as its Notes content.

### Expected behaviour

# https://github.com/webcompat/web-bugs/issues/120964#issuecomment-1518197248

<blockquote>

@softvision-raul-bucata, cookies were accepted if prompted.

![image](https://user-images.githubusercontent.com/42837531/233709552-92ef1107-acab-4a14-bf01-653ba66be00d.png)

I just tried `firefox --safe-mode`, though, and login worked, so I'll find the actual culprit myself. Thanks.

</blockquote>

### Actual behaviour

![https://wim.nl.tab.digital/apps/tasks/#/calendars/tasks/tasks/7901506C-5EED-4FF9-96CA-FAB79773D3BE.ics](https://github.com/nextcloud/tasks/assets/42837531/a41f7390-6613-4b2c-bdda-292f05b976e7)

The image is not rendered, and the

```html
<blockquote></blockquote>
```

tags are ignored.

#### Browser
```log
PS /home/rokejulianlockhart> firefox -v
Mozilla Firefox 113.0.1
PS /home/rokejulianlockhart>
```

#### Operating system
```log
PS /home/rokejulianlockhart> uname -a
Linux RQN6C6 6.3.2-1-default #1 SMP PREEMPT_DYNAMIC Mon May 15 15:59:38 UTC 2023 (70ea6f6) x86_64 x86_64 x86_64 GNU/Linux
PS /home/rokejulianlockhart>
```

**Comment by beedell-roke** [comment]
@raimund-schluessler,

> The Notes section uses markdown, and `<blockquote>` is not a valid markdown element. The corresponding element would be `>`. So this is the equivalent markdown markup

`<blockquote>` is valid Markdown almost everywhere, because by convention nowadays *all* HTML is valid Markdown. See [`stackoverflow.com/a/55558811`](https://stackoverflow.com/a/55558811/9731176#:~:text=since%20you%20can%20directly%20use%20html%20in%20markdown%20it%20could%20be%20considered%20a%20superset%20of%20html) for more information. Nextcloud's Markdown processor is the sole one that thus far hasn't been able to render this element. At the very least, the lack of HTML support is rather disappointing, considering that it's a feature in most processors.

> If I put this in the notes field, I get the behaviour you want, including a correctly embedded image.

I suppose that that must mean that the version of Nextcloud the server that I'm using – [`wim.nl.tab.digital`](https://wim.nl.tab.digital) – uses contains a bug that has subsequently been remediated. Do you know a method of ascertaining the server version (as a non-administrative user) to confirm?

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler,
> 
> > The Notes section uses markdown, and `<blockquote>` is not a valid markdown element. The corresponding element would be `>`. So this is the equivalent markdown markup
> 
> `<blockquote>` is valid Markdown almost everywhere, because by convention nowadays _all_ HTML is valid Markdown.

Yeah, you are right. The "Nextcloud Markdown processor" is `markdown-it`, which supports rendering HTML elements. But if you enable this, one needs to sanitize the note, because otherwise one will be vulnerable to XSS attacks. I am a bit reluctant to go this path, to be honest.
 
> > If I put this in the notes field, I get the behaviour you want, including a correctly embedded image.
> 
> I suppose that that must mean that the version of Nextcloud the server that I'm using – https://wim.nl.tab.digital – uses contains a bug that has subsequently been remediated. Do you know a method of ascertaining the server version (as a non-administrative user) to confirm?

I don't really think it has much to do with the server version, because the rendering happens in your browser.

**Comment by rokejulianlockhart** [comment]
<blockquote>
<blockquote>
<blockquote>

If I put this in the notes field, I get the behaviour you want, including a correctly embedded image.

</blockquote>

I suppose that that must mean that the version of Nextcloud the server that I'm using – [wim.nl.tab.digital](https://wim.nl.tab.digital/) – uses contains a bug that has subsequently been remediated. Do you know a method of ascertaining the server version (as a non-administrative user) to confirm?

</blockquote>

I don't really think it has much to do with the server version, because the rendering happens in your browser.

</blockquote>

@raimund-schluessler, then what could be the issue regarding the image? I've the same Markdown code in that task note that I do here:

![image](https://github.com/nextcloud/tasks/assets/42837531/a70e3b5c-9e09-4f55-809f-c883abfaffb3)

```markdown
![image](https://user-images.githubusercontent.com/42837531/233709552-92ef1107-acab-4a14-bf01-653ba66be00d.png)
```

![image](https://user-images.githubusercontent.com/42837531/233709552-92ef1107-acab-4a14-bf01-653ba66be00d.png)

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler, then what could be the issue regarding the image?

This is very likely a feature of the Content Security Policy set. You should see blocked request to this image in the Network tab of the Web Developer Tools in your browser.
Please ask for support in the forum how to configure the CSP.

**Comment by beedell-roke** [comment]
> [`#issuecomment-1873487855`](https://github.com/nextcloud/tasks/issues/2274#issuecomment-1873487855)

@raimund-schluessler, Indeed — <q>21: `45:05.637` Content - Security - Policy: The page's settings blocked the loading of a resource at [`https://user-images.githubusercontent.com/42837531/233709552-92ef1107-acab-4a14-bf01-653ba66be00d.png`](https://user-images.githubusercontent.com/42837531/233709552-92ef1107-acab-4a14-bf01-653ba66be00d.png) ("`img-src`"). `NotesItem.vue:96`</q>. Can this solely be remediated by the host? I don't host my own instance, so there's no point in my researching CSP policies if I can't change them.

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler, Indeed - 21: 45:05.637 Content - Security - Policy: The page's settings blocked the loading of a resource at https://user-images.githubusercontent.com/42837531/233709552-92ef1107-acab-4a14-bf01-653ba66be00d.png ("img-src"). NotesItem.vue:96. Can this solely be remediated by the host? I don't host my own instance, so there's no point in my researching CSP policies if I can't change them.

As far as I know, this is a setting of the server / host whether they allow "img-src" or not. But I am not an expert on the CSP settings of Nextcloud and it might be worthwhile to ask in the forum about this.

**Comment by beedell-roke** [comment]
> [`#issuecomment-1873495567`](https://github.com/nextcloud/tasks/issues/2274#issuecomment-1873495567)

@raimund-schluessler, I've posted [`help.nextcloud.com/t/177969`](https://help.nextcloud.com/t/csp-configuration-performed-by-user-or-host/177969?u=rokejulianlockhart). Thanks.
