### ISSUE TITLE
[Feature Request] Move notes to Details tab

### ISSUE THREAD

**Issue by meichthys** [nextcloud/tasks#2279]
### Expected behavior
Ideally the notes on the task would be visible alongside other note details (date, title, priority, etc) just by selecting the task.
![image](https://github.com/nextcloud/tasks/assets/10717998/dcce4a19-1728-4eff-a5c2-0c9bcb927978)

### Actual behavior
Currently we have a 'Notes' tab in the sidebar (or the notes icon in the list view) that must be selected in order to view the notes.

### Additional Information
This would also reduce the number of tabs in the sidebar in anticipation for #34 which would likely need a tab for the complexities of recurrence.

**Comment by raimund-schluessler** [comment]
We put the notes in a separate tab because otherwise they don't have much space (without scrolling). E.g. on my display, the notes section would only have 200 px of height available, which is quite little. And if you need to scroll, other details will be out of view as well.

Having three tabs with the tab for #34 would still be ok, I think. Other apps have sometimes even more.
