### ISSUE TITLE
Feature Request: When creating a task in "Manual sort" mode, create it at the top of the list

### ISSUE THREAD

**Issue by ryantrinkle** [nextcloud/tasks#2345]
### Steps to reproduce
1. Go into the Tasks view
2. Change the sort order to "Manually" with the arrow pointing upward
3. Create a task.

### Expected behaviour
I would like the task to appear at the top of the list.  (Of course, this could be configurable.)

### Actual behaviour
The task appears at the bottom of the list, and has to be manually dragged to the top.

### Server configuration

**Operating system**: Linux (NixOS)

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 27.0.1

**Tasks version:** 0.15

**Updated from an older Nextcloud or fresh install:** Updated

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/nextcloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by khariche** [comment]
Same issue here, linux (kde neon), firefox.
Makes the web interface pretty useless with my workflow. What a pity!

**Comment by raimund-schluessler** [comment]
The sorting happens based on the number of seconds passed since `2001-01-01-00:00:00`. This follows the way Apple handles this in their todo apps.

Tasks created later get larger numbers and show up at the bottom of the list when sorting normally (arrow up), since simply sort this as integers are sorted. I admit, it might have been better to revert the sorting in this special case and show larger numbers at the top by default. However, we will not change this, as it would break sorting for people that have adapted to this behavior.

So, as solution, you simply need to revert the sort order (arrow down) and manually sort your tasks according to this. New tasks will show up at the top of the list, you will just have to live with the arrow pointing down, instead of up.

**Comment by raimund-schluessler** [comment]
> Same issue here, linux (kde neon), firefox. Makes the web interface pretty useless with my workflow. What a pity!

This is a bit of a harsh statement. If you cannot use an app, due to such a tiny detail (an arrow points down, instead of up), I feel sorry for you. I assume you will have a hard time using any program then. And, guess what, this app was not specifically designed for you or your workflow, and other people might have other workflows for which Tasks works just fine. If that bothers you, I propose you look for another free-of-charge app whose devs will be happy to design your favorite app.

**Comment by khariche** [comment]
> > Same issue here, linux (kde neon), firefox. Makes the web interface pretty useless with my workflow. What a pity!
> 
> This is a bit of a harsh statement. If you cannot use an app, due to such a tiny detail (an arrow points down, instead of up), I feel sorry for you. I assume you will have a hard time using any program then. And, guess what, this app was not specifically designed for you or your workflow, and other people might have other workflows for which Tasks works just fine. If that bothers you, I propose you look for another free-of-charge app whose devs will be happy to design your favorite app.

I am really sorry that came across as harsh, it was not meant to be... It is because I really value this app that the sorting detail is disappointing to me. I thank you for your hard work and appreciate the explanation and proposed solution, but the issue I am facing is not simply a matter of inverting the arrow in the web interface. 
I realize I could have been more explicit when I mentioned my workflow: I use the tasks.org android app to sync via DAVx5 with your app, and the issue is that this android app, when in manual sorting, works exactly opposite to yours: when creating a new task, it appears at the top of the list, and there is no option, contrary to your app, to invert the order of the manual sorting. Even if I asked the developer of the tasks.org app to add an option to invert the sorting in "manual mode", the same issue might appear: then tasks would be added at the end of the list if tasks are sorted the opposite way.
Do you see any other solution? Would it be possible to add an option to let the user choose whether new tasks are created at the top or the bottom of the list independently of the orientation in "manual sorting"?
Thanks in advance.

**Comment by DoS007** [comment]
Hey there, wanted to create an issue for than and found this:

@raimund-schluessler :
*Tried the workaround, incompatible with tasks.org:* I'm using DAVx on Android with tasks.org (DAVx only supports 3: opentasks -> no subtasks; jtx Board ->[no "dense" view possible](https://github.com/TechbeeAT/jtxBoard/discussions/1241), and tasks.org). In tasks.org, new tasks are also added on top in manual sorting by default, which I like. When I now try the workaround using the reverse manual ordering, then new tasks are shown on top using nextcloud tasks on nextcloud. But in tasks.org only "manual sorting" is possible and not reverse "manual sorting", so in tasks.org the task still is on the bottom (and possibly on other apps).

> [...], it might have been better to revert the sorting in this special case and show larger numbers at the top by default. However, we will not change this, as it would break sorting for people that have adapted to this behavior. [...]

I like the *weighing/consideration* (new behaviour for old users vs advantage of change). I personally would think that new behaviour wouldn't be to drastic and it's easier to drag a new item on top vs an item on a long list on the bottom (in a big list with default view / on top the new item isn't visible without scrolling). Also i would think that people who use manual sorting in a big list more often want new tasks to be near the top than to be near the bottom (but that could be subjectivly).

Or alternativly maybe add an option for that behavoiur?

Btw. thanks anyway, without your app nextcloud would be less feature rich.
