### ISSUE TITLE
wrong calendar week when setting start or due date

### ISSUE THREAD

**Issue by macpac59** [nextcloud/tasks#2366]
### Steps to reproduce

1. Entering a wrong start or due date via the dialogue in a task
2. The wrong calendar week (+1) appears in the miniature calendar while the correct one is shown in the main calendar tool
3. Maybe this is an issue of having chosen a wrong country?

### Expected behavior

the correct calendar week should be shown

### Actual behaviour

a wrong calendar week is shown

### Tasks app version

0.15.0

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

26.0.1

### Updated from an older installed version or fresh install

None

**Comment by raimund-schluessler** [comment]
Could you maybe post a screenshot of what is wrongly shown? I don't really understand the issue at the moment. Thanks!

**Comment by macpac59** [comment]
[image: grafik.png]

See here please: The first calendar week of 2023 should only start on the
2nd of January 2023.

week 01: the week with the starting year's first Thursday in it (the formal
ISO definition),
https://en.wikipedia.org/wiki/ISO_8601

By the way: A really great app!!!


Am Mo., 8. Jan. 2024 um 23:41 Uhr schrieb Raimund Schlüßler <
***@***.***>:

**Comment by raimund-schluessler** [comment]
![Screenshot 2024-01-09 at 13-17-51 Aufgaben - Nextcloud](https://github.com/nextcloud/tasks/assets/2496460/3a82faa5-b0c7-4317-a55d-ea1db874ed6a)

Thanks for the clarification. I uploaded a screenshot, because yours somehow didn't show up.

We use the datepicker component from `nextcloud/vue`. As it unfortunately resides in a different orgranization, I will close this issue here and open a new one there (I cannot simply move it).

**Comment by raimund-schluessler** [comment]
See https://github.com/nextcloud-libraries/nextcloud-vue/issues/5044.

**Comment by raimund-schluessler** [comment]
Fixed in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5045, but needs a new release of nextcloud/vue.
