### ISSUE TITLE
Display actual amount of tasks, not “999+”.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [nextcloud/tasks#2416]
### Is your feature request related to a problem? Please describe.

The sidebar displays "999+" when the amount of tasks is more than 999.

### Describe the solution you'd like

Display the actual amount of tasks.

**Comment by raimund-schluessler** [comment]
This is a guideline from the Nextcloud developer documentation, that states values higher than 999 should be given as 999+:
https://docs.nextcloud.com/server/latest/developer_manual/html_css_design/navigation.html#counter

For me, personally, this doesn't really matter, since I barely have 50 open tasks at a time. However, if you want this changed, please get a PR approved in the documentation repo https://github.com/nextcloud/documentation. If this guideline is adjusted there, I am happy to follow  and implement it.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/tasks/issues/2416#issuecomment-1873479119

@raimund-schluessler, I'm not a programmer, so I can't create a PR. However, I doubt that any PR would be approved based upon the text you cite (nor, ideally, would I want it to be, if in contravention to those guidelines). Consequently, do you know where I can propose to change https://docs.nextcloud.com/server/latest/developer_manual/html_css_design/navigation.html#counter:~:text=the%20counter%20should%20be%20limited%20to%20999%20and%20turn%20to%20999%2B%20if%20any%20higher%20number%20is%20given?

**Comment by raimund-schluessler** [comment]
In the repository of the documentation I linked above.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/tasks/issues/2416#issuecomment-1873513988

I have filed https://github.com/nextcloud/documentation/issues/11418#issue-2061870486, @raimund-schluessler. Until then, https://github.com/nextcloud/tasks/issues/2395#issuecomment-1873562957.

**Comment by RokeJulianLockhart** [comment]
https://github.com/nextcloud/tasks/issues/2395#issuecomment-1873562957.
