### ISSUE TITLE
Make Tasks Nextcloud Hub 8 (v 29) compatible

### ISSUE THREAD

**Issue by Alexandero89** [nextcloud/tasks#2536]
### Describe the solution you'd like

Nextcloud Hub 8 (version > 29) just released and the Tasks app is shown to be not compatible with this version.
Would be awesome if you could release a new and compatible version.
Thanks in advance!

**Comment by fm-sys** [comment]
+1

In fact, that's the only reason I haven't updated to NC 29 yet. 

OT:
Even if it's listed as incompatible, is it still possible to update the NC server and continue using the app, or will incompatible apps automatically get disabled?

**Comment by raimund-schluessler** [comment]
You should be able to "enable incompatible app". There is no reason why Tasks 0.15.0 shouldn't work with NC29.

**Comment by reox** [comment]
> You should be able to "enable incompatible app". There is no reason why Tasks 0.15.0 shouldn't work with NC29.

I tried this several times but NC wouldn't let me enable it because "the app makes the server unstable"....
However I found out that you can enable it via occ: `occ app:enable tasks` - and it looks like it is working with NC29.

**Comment by micah** [comment]
> > You should be able to "enable incompatible app". There is no reason why Tasks 0.15.0 shouldn't work with NC29.
> 
> I tried this several times but NC wouldn't let me enable it because "the app makes the server unstable".... However I found out that you can enable it via occ: `occ app:enable tasks` - and it looks like it is working with NC29.

If you do that, you get this:

`App "Tasks" cannot be installed because it is not compatible with this version of the server.`

**Comment by reox** [comment]
Okay, maybe you have to click on "enable incompatible app" in the GUI before and then enable it via occ...
There is also this option for `occ app:enable`:
```
  -f, --force           enable the app regardless of the Nextcloud version requirement
```

**Comment by dvzrv** [comment]
Hi! :wave: 

I package nextcloud for Arch Linux and would like to note, that this app is now blocking our upgrade to nextcloud 29.
Due to how nextcloud signs/ locks the contents of the release artifacts we are not able to rebuild an app from scratch, but have to rely on the release artifacts of each app/ nextcloud itself.
A while ago we have introduced a custom version pinning method which ensures, that all apps in the Arch Linux repositories are in fact compatible with the currently available nextcloud version.

That all being said, this means that the current package for this project is not compatible with the nextcloud version we have waiting in staging and can not be rebuild against that version either.

I wanted to add this as a data point on why it may not be possible to update to nextcloud 29 due to this project.

**Comment by raimund-schluessler** [comment]
Sorry to hear that. I will hopefully have time to take care of a new release on the weekend.

**Comment by raimund-schluessler** [comment]
So, I had time to fix some of the remaining issues for the next release 0.16.0 of Tasks. Since this is going to be a big release, with new features and the migration to vue3, a bit of extra testing would be good.

I packed a release file which you can download here:
[tasks.tar.gz](https://github.com/nextcloud/tasks/files/15210931/tasks.tar.gz)

One issue is already known, dropping tasks onto the left sidebar does not work yet, see #2562

Please report any other issue you notice. Thanks a lot!

**Comment by ace02000** [comment]
Hi @raimund-schluessler 
thank you for your great work :)

**Comment by raimund-schluessler** [comment]
Tasks v0.16.0 was released to the appstore just now.
