### ISSUE TITLE
[Feature Request] Implement GUI for lists and tasks trashbin

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#29]
see https://github.com/nextcloud/server/issues/1662

**Comment by bcutter** [comment]
+10

**Comment by teneighty-yvr** [comment]
I would be satisfied with a sanity check by an "are you sure?" prompt. 

A trashbin is better because you can restore deleted tasks a day or a week later, maybe more, which can definitely happen for some users. I use an archive list instead, but I have deleted a task by accident.

@tcitworld has also suggested using the same time-based confirmation currently used when deleting lists and calendars. If you realize immediately what you've done you have 5 seconds or so to cancel it. I get that it's probably the easiest to implement becuase it can be contained entirely within the client side application and only requires a small amount of extra code to delay sending the delete order to the server.

I think the best solution would be one that also protects other applications accessing tasks through DAV, but that might be in nextcloud/server scope?

Just to add how important tasks are for my use case, I use them a lot in the project management field in a construction contracting company with million dollar projects. Maybe there are better ways but this is simple, standardized, portable, open source, we use Nextcloud anyway for files, and tasks is working really well for me. I keep a lot of notes in each tasks. A lot. Checklist (thank you markdown), progress, developments, who I need to follow up with and when. Often these notes span several months. Losing one task to a mis-click can be a very big deal.

Nextcloud/server : 20.0.5
Tasks : 0.13.6
