### ISSUE TITLE
Sorting priority not taking priority value into account

### ISSUE THREAD

**Issue by rrudnicki** [nextcloud/tasks#427]
### Steps to reproduce
1. Add new task "A".
2. Add new Task "B".
3. Set priority of task "A" to 1.
4. Set priority of task "B" to 2.
5. Sort priority descending.

### Expected behaviour
List should show "B" first, and "A" second.

### Actual behaviour
List shows "A" first, and "B" second.

### Server configuration
**Operating system:**
Debian 9.9

**Web server:**
Apache 2.4.25

**Database:**
MariaDB 10.1.38

**PHP version:**
7.2.18

**Nextcloud version:** (see Nextcloud admin page)
15.0.7 (also tested on 16.0.1)

**Tasks version:** (see Nextcloud apps page)
0.10.1

**Updated from an older Nextcloud or fresh install:**
updated

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

**Are you using encryption:** yes/no
yes

**Comment by raimund-schluessler** [comment]
This is how it is supposed to be. Sorting by priority descending means, that tasks with high priority are shown at the top, low priority at the bottom.

Following the CalDAV standard RFC5545 (see https://tools.ietf.org/html/rfc5545#section-3.8.1.9), the order of priorities (from high to low) is 1, 2, 3, 4, 5, 6, 7, 8, 9, 0.
So the app behaves as it should, since we follow the standard (now). This has changed compared to v0.9.8 of the app, which behaved differently, but didn't follow the standard correctly.

If I got your report wrong, please speak up.
