### ISSUE TITLE
Feature req: Configure custom collections

### ISSUE THREAD

**Issue by varac** [nextcloud/tasks#468]
It would be great if Nextcloud Tasks would allow custom collections.
I.e. I'd love to add a collection that only shows tasks i.e. :

- Important tasks
- Start-date not in the future
- Eventually filtered by one or more catogories

**Comment by raimund-schluessler** [comment]
I think this is a reasonable feature, but quite similar to #220, so lets discuss this there.

The solution I have in mind for this issue is to allow searching for certain properties, like "tag: Work, starred: <5" and then enable pinning a search as a smart list.

Btw.: there already is a smart list for important tasks and the "current" smart list shows tasks with a due or start date that has already passed.
