### ISSUE TITLE
Can not interact with all task lists anymore

### ISSUE THREAD

**Issue by robingenz** [nextcloud/tasks#479]
### Steps to reproduce
1. Add a task list named "Persönlich"
2. Update to Nextcloud Tasks version 0.10.0

### Expected behaviour
It should be possible to interact with the task list without any problems.

### Actual behaviour
Since release v0.10.0 I can not interact with all task lists anymore. When I access my task list named "Persönlich", only a blank area (empty `<div class="content-wrapper"></div>`) is displayed (See screenshot).
![blank-area](https://user-images.githubusercontent.com/13857929/60753142-add4e200-9fce-11e9-8ba7-b13893d629f9.PNG)
The associated url is: https://server.tld/apps/tasks/#/calendars/pers%C3%B6nlich

### Server configuration

**Operating system**: Ubuntu 18.04.2 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** v7.2

**Nextcloud version:** v16.0.2

**Tasks version:** v0.11.0

**Updated from an older Nextcloud or fresh install:** older install

**Signing status:**

```
No errors have been found.
```

### Client configuration
**Browser:** Firefox 67 and Chrome 75

**Operating system:** Windows 10 and Ubuntu 18 Desktop

**Comment by raimund-schluessler** [comment]
How did you create this task list? It shouldn't have any special characters in its url. When I create one with NC16.0.2 and Tasks 0.9.8, the url reads `/nextcloud/index.php/apps/tasks/#/calendars/persnlich`.

**Comment by robingenz** [comment]
The task list is about 3 years old. I created the list along with the calendar in the Calendar app. If I create a new task list with special characters in the current version, they are not part of the url either.

**Comment by raimund-schluessler** [comment]
Hm, I can reproduce this issue when I add a percent-encoded character into the URI, like `%C3%B6`. The problem is that this character will be decoded to `ö` and the calendar cannot be found by its ID anymore, because `%C3%B6` != `ö`. Sadly, i don't know how to fix this yet.

**Comment by robingenz** [comment]
Thanks for your help.
I fixed it in sql by removing the `ö` from the `uri` attribute of the record.
Databse table: `oc_calendars`
Maybe it helps others.

**Comment by raimund-schluessler** [comment]
@robingenz I (partially) fixed the issue in #480. The only problem which remains is, that the initial navigation for such special URIs will not work. This means reloading the app will lead to a blank calendar view, but the calendar will appear as soon as you click the link in the left sidebar. This is likely due to https://github.com/vuejs/vue-router/issues/2725

I packed a version including the fix: [tasks.zip](https://github.com/nextcloud/tasks/files/3365428/tasks.zip). Could you please check whether the version in this zip file solves the problem? Please recreate your issue by putting the `ö` back into the `uri`, making sure the problem reoccurs with v0.11.0 and check whether the fixed version solves it.

**Comment by robingenz** [comment]
@raimund-schluessler I have tested it. Your fix solves my problem. But as you said, initial navigation does not work for such special URIs.

**Comment by raimund-schluessler** [comment]
I think fixing the initial nav needs to be done upstream. But #480 at least enables working on such calendars at all.
