### ISSUE TITLE
Tasks not added to calendar

### ISSUE THREAD

**Issue by wdfee** [nextcloud/tasks#507]
Currently in Nextcloud 16.0.3 and Tasks 0.11.0 the calendar is correctly linked to tasks, but the created tasks (with start / due date) do not show up as events in calendar app. 
The downloaded ics file counts only one event to add (even if there are more) but doesn't add any events to the calendar. The file imports the correct number of tasks to the reminders list but it's always the same first added task. (So this one task shows up x times in reminders list.)

PHP 7.2.20

**Comment by raimund-schluessler** [comment]
> Currently in Nextcloud 16.0.3 and Tasks 0.11.0 the calendar is correctly linked to tasks, but the created tasks (with start / due date) do not show up as events in calendar app.

Showing tasks with a start and due date in a calendar has to be implemented in the Calendar app, see https://github.com/nextcloud/calendar/issues/28 for the details.

> The downloaded ics file counts only one event to add (even if there are more) but doesn't add any events to the calendar. The file imports the correct number of tasks to the reminders list but it's always the same first added task. (So this one task shows up x times in reminders list.)

Could you please explain this part of the problem a bit more clearly? I don't understand what is the issue here. The Tasks app doesn't support importing tasks and what do you mean with reminders?

**Comment by wdfee** [comment]
Thanks for your pretty fast answer and your link to this pretty matching thread.

I'm talking about the Mac OSX app "reminders" ("Erinnerungen" in German). On Mac OS calendar app and reminders app are seperated, the reminders app can import ics files as a list, the calendars app would import this as events. Is that a little bit clearer?

If I have a task list for example:
1. Do ABC, until due date Juli 21st 2019
2. Do CEF, until due date Juli 28th 2019
3. Do GHI, until due date August 3rd 2019
...and if I export this task list as ics file
-> the calendar app says "there is 1 event to import" and imports nothing,
-> the reminders app imports a list looking like this:
1. Do ABC, until due date Juli 21st 2019
1. Do ABC, until due date Juli 21st 2019
1. Do ABC, until due date Juli 21st 2019

**Comment by raimund-schluessler** [comment]
Sorry, but your issue doesn't involve the Tasks app at all, and we cannot give support for any other calendar or task related program (especially not MacOS Reminders and Calendar, since I don't own a Mac). --> closing this issue then.

Anyway, a few comments.

Your ICS file should look something like this:
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:Test
X-APPLE-CALENDAR-COLOR:#2e2e2e
BEGIN:VTODO
UID:a9269c60-a2dd-4d93-8d75-aec3991f2114
CREATED:20190717T090308
LAST-MODIFIED:20190717T090315
DTSTAMP:20190717T090315
SUMMARY:CEF
DUE:20190728T100000
END:VTODO
BEGIN:VTODO
UID:49a3b937-6f6a-4e64-9c1b-1788557a0ac7
CREATED:20190717T090248
LAST-MODIFIED:20190717T090259
DTSTAMP:20190717T090259
SUMMARY:ABC
DUE:20190721T100000
END:VTODO
BEGIN:VTODO
UID:ac44d238-dc84-4d41-9471-5af0aad1e109
CREATED:20190717T090321
LAST-MODIFIED:20190717T090331
DTSTAMP:20190717T090331
SUMMARY:GHI
DUE:20190803T100000
END:VTODO
END:VCALENDAR
```

As you see, for every entry it is specified that it is of type `VTODO`, marking this entry as a "task". When you try to import this using the MacOS Calendar app it will likely do nothing, since there is no event in the ICS (which would be of type `VEVENT`. So it is expected, that the Calendar app imports nothing (I don't know why it states it will import 1 event, seems like a bug, or maybe there actually is an event in the ICS file).

The Reminder app should import all `VTODO` in the ICS, again, why it only imports one multiple times, I don't know (bug?).

Please make sure your ICS file really contains all tasks you expect it to.
