### ISSUE TITLE
Enable checks for master branch

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#508]
@MorrisJobke Could you check whether it is possible to enable checks like Codecov an Travis on the master branch, like it is in the Contacts repo for example? There you see multiple checks if you click on the checks arrow.

![Screenshot-2019-7-17 nextcloud contacts](https://user-images.githubusercontent.com/2496460/61357555-ccfa2c00-a878-11e9-8ca3-5cf0fd37c680.png)

Also, the Codecov badge does not show anything on the Tasks repo? Do you have an idea why?

**Comment by MorrisJobke** [comment]
Usually there is nothing to do from my side, because it is only a config of Travis/Codecov/etc ... there you typically can exclude some branches, that should not run the CI jobs. I can't see this for codecov for example here.

Also it shows up for the ones that were checked in the PR itself:

<img width="929" alt="Bildschirmfoto 2019-07-17 um 11 35 56" src="https://user-images.githubusercontent.com/245432/61364952-13ef1e00-a887-11e9-89cc-aae88e877674.png">


For the directly pushed ones I found out that there is indeed a setting inside the Travis page and I enabled it.

**Comment by raimund-schluessler** [comment]
@MorrisJobke Thanks for taking care of this. Could you maybe also check whether you could enable Codecov for the Tasks repository? I send an request to the Nextcloud organization for enabling the Github app.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Thanks for taking care of this. Could you maybe also check whether you could enable Codecov for the Tasks repository? I send an request to the Nextcloud organization for enabling the Github app.

Codecov is just where the data is dumped. Most likely from travis builds and then it should also show up

**Comment by raimund-schluessler** [comment]
Travis is configured for codecov already and uploading reports works. But it would be nice if codecov reports as a check like Travis and Scrutinizer (and as it is in the contacts repo).

**Comment by MorrisJobke** [comment]
> Travis is configured for codecov already and uploading reports works. But it would be nice if codecov reports as a check like Travis and Scrutinizer (and as it is in the contacts repo).

Ah ... I just noticed that this is not added here.

**Comment by MorrisJobke** [comment]
Enabled.
