### ISSUE TITLE
[Feature Request] (more) compatibility with iOS13

### ISSUE THREAD

**Issue by verymilan** [nextcloud/tasks#627]
Hey there, iOS13 brings a new Reminders-App, that supports sublists for example. 
I was wondering if it was possible to access those features with the Nextcloud account (in the future), as they currently are only accessible with the iCloud-Account for me.

Regards

**Comment by raimund-schluessler** [comment]
Sadly this won't be possible, because Apple decided to not use the CalDAV protocol anymore for syncing their Reminders (via iCloud). So while Reminders in iCloud offer more functionality (e.g. subtodos), we won't be able to access them from Nextcloud. However, CalDAV sync to Nextcloud still works with the Reminders app. And in principle Apple could decide to support new features with CalDAV sync as well, since the CalDAV protocol would support them (obviously, since Nextcloud Tasks already has it implemented).

So unless Apple decides implement these features for lists using CalDAV as well, there won't be a better compatibility.

Also see https://github.com/nextcloud/server/issues/17190.

**Comment by verymilan** [comment]
Alright, thank you!

**Comment by atharapos** [comment]
Wouldn't it be possible to access the source code that accesses the iCloud server from iCloud and use this code to provide an interface with iCloud and mesh this app interface with that code to provide the required functionality? I believe the code is mainly client sided and in javascript. The main javascript script for iCloud is quite long (80,000 lines), but the reminders part of this script is not that large. There is also a icloudkit.js I believe it interfaces with that is about 8,000 lines. I believe you could use these two files to interface with iCloud and provide requested functionality. But I could be wrong.

I am currently doing a Web Programming course at University and would be happy to help with this aspect once I have completed it in Feb 2020.
