### ISSUE TITLE
Update the design

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/tasks#664]
The sidebar looks a litte bit outdated. 
Maybe we could do some polish and use elements of the deck or calendar app (each from the vue branch):

Deck:
![grafik](https://user-images.githubusercontent.com/24530680/66557874-e8f92b00-eb52-11e9-9c3d-6c28865bed07.png)

---

Calendar:
![grafik](https://user-images.githubusercontent.com/24530680/66558377-c0bdfc00-eb53-11e9-8f45-ca9df158a042.png)

**Comment by raimund-schluessler** [comment]
I also thought about updating the sidebar. Especially I would like to

-  introduce tabs since the amount of information in the sidebar increased over time
- add an illustration same as the Calendar app does it now

What I want to keep as it is, is that I want to show input elements only after the user clicks on something he wants to edit. I find all these input fields visually noisy.

**Comment by jakobroehrl** [comment]
@raimund-schluessler 
I would like to help here, maybe after the Deck VUE migration is done.

**Comment by timkrief** [comment]
On top of the sidebar, the task list was a bit intimidating for me.

I don't know if this could help, but I made a custom CSS style-sheet for my personal use. It's full of tricks right now since I'm only using a CSS on top of what's already existing, but if the general direction is of your liking, I'm willing to properly change the style of the app to make a PR.
![image](https://user-images.githubusercontent.com/14089949/87147429-f2afea80-c2ac-11ea-8797-1d2c074ce2b0.png)
(the background could be removed I just like bright colors!)
![image](https://user-images.githubusercontent.com/14089949/87147655-4ae6ec80-c2ad-11ea-99ea-c6940985170e.png)

**Comment by raimund-schluessler** [comment]
I think it looks very nice, but it somehow doesn't match the overall nextcloud style. What do the @nextcloud/designers think?

**Comment by timkrief** [comment]
Maybe the background could get in the way of judging the style, so here's with a neutral one: 
![image](https://user-images.githubusercontent.com/14089949/87151419-132f7300-c2b4-11ea-8b94-fd5f56600038.png)

I'm open to potential feedback and changes to try and fit to the overall nextcloud style :smiley:

**Comment by juliushaertl** [comment]
I think that it would fit quite good if the shadows and border radius would just use the amount we have by default in our css variables, worth a try with that imo.

**Comment by timkrief** [comment]
Ok, I used the CSS variables as advised and the draft looks like this now: 
![image](https://user-images.githubusercontent.com/14089949/87154950-63113880-c2ba-11ea-8b6a-c8a1cd573a84.png)

**Comment by raimund-schluessler** [comment]
A bit of feedback:
- Whether we want to introduce a different background would need to be discussed with @nextcloud/designers. I know there is the idea to change it to `background-color: var(--color-background-dark);` for Deck https://github.com/nextcloud/deck/issues/1892, so it might make sense to do that for Tasks as well to keep it consistent.
- I like the coloring and style of the checkboxes. It looks friendly to have a bit more color in the task list. However, we had a discussion to unify the checkbox appearance in https://github.com/nextcloud/tasks/issues/506 and https://github.com/nextcloud/tasks/issues/572, so changing it would partly reverse that effort. I don't know if that is desired. If we just change the border (color, thickness and border-radius) of the box, it might be ok.
- I would like to keep the star icon, as it's an active icon allowing to toggle the importance of a task without opening the sidebar. I know you moved the color to the checkbox, but that doesn't make up for the missing toggling option.
- Is it intended that the subtasks overlap their parents? It looks a bit weird imo and we do that nowhere else afaik.

Also @jancborchardt here.

**Comment by timkrief** [comment]
Thanks for the feedback!

- For the background, that's exactly what I did here, I used `background-color: var(--color-background-dark);`
- For the checkbox, I just changed the attribute you mentioned and the color for the priority
- The star icon was always using a priority 1 so I was not using it because I'm always using another priority level by default and 1 when there's something really important. However I can understand why one would want to keep it if always using only one priority value. Keeping it then creates redundant information since the colors will be at two places at once. Maybe introducing a setting to toggle between the two ways of displaying the priority could be interesting. What I really like in having the check box colored is that you can clearly know the priority when reading the task (proximity between the text and the color that informs you)
- The sub-task overlapping their parents was not intended, it's fixed.
- The change in priority colors was not my intention, I just chose colors randomly. As I said before, it was just a personal CSS style initially. Here's a version with the right colors:

![image](https://user-images.githubusercontent.com/14089949/87161739-3dd5f780-c2c5-11ea-919f-4f37ec14cce2.png)

Keep in mind it's a draft I made using a custom CSS stylesheet. As I said, if the general direction is ok, then it will be made as part of a proper PR.

**Comment by jancborchardt** [comment]
@timkrief that looks all really nice! :) Only one piece of feedback on that last screenshot: It’s a bit strange that the shadow of parent elements overlaps the first child, since they have the same amount of shadow. In earlier screenshots it didn’t overlap and looked a bit nicer.

Also your other designs from earlier look quite nice! :) As the others said it is first good to use the main variables, and then if you like we can see if it makes sense to change the variables.

> As I said, if the general direction is ok, then it will be made as part of a proper PR.

Sounds great! By the way, we have a Nextcloud Talk instance with a "Design team" and "Tasks team" room – I can invite you there with a guest account?

**Comment by timkrief** [comment]
Thanks for the feedback. Of course you can!

**Comment by Bugsbane** [comment]
Overall I'd say it's really nice and a definite step forward.

Something that I find conceptually doesn't make sense to me though, is that there are gaps between a task and it's subtask. These two things are conceptually linked (one is part of the other) and yet there's a gap between them.

On the other hand, a sub task and an unrelated shallower level task are conceptually unrelated, but they're shown as linked, with no gap between them.

I would suggest switching this, so there is no gap between a task and it's subtask (as they're connected), but a gap between a subtask and a task of a shallower level (as they're unrelated). Here's my imperfect mockup to demonstrate what I mean:

![tasks](https://user-images.githubusercontent.com/401733/87204874-03c02200-c2d4-11ea-881e-3d2851480f07.png)

**Comment by timkrief** [comment]
Oh sorry for the misunderstanding @Bugsbane It's wasn't a gap, it was a shadow, ignore it, as @jancborchardt said it was nicer without it.
![image](https://user-images.githubusercontent.com/14089949/87210531-2410d080-c316-11ea-8e83-910a7444ff75.png)
(the gaps are making me really confused as if random tasks were separated from the others for no reason ^^)

**Comment by raimund-schluessler** [comment]
> Oh sorry for the misunderstanding @Bugsbane It's wasn't a gap, it was a shadow, ignore it, as @jancborchardt said it was nicer without it.
> ![image](https://user-images.githubusercontent.com/14089949/87210531-2410d080-c316-11ea-8e83-910a7444ff75.png)
> (the gaps are making me really confused as if random tasks were separated from the others for no reason ^^)

I think this looks really nice. A PR would be great.

**Comment by skjnldsv** [comment]
Just passing by and love all the great support and feedback everyone gave here! Thanks for being part of this awesome community everyone!! :hugs:

**Comment by ma12-co** [comment]
Great stuff :)
some remarks from my side: 

- I think that the idea of separation mentioned [here](https://github.com/nextcloud/tasks/issues/664#issuecomment-656903971) is really nice, but I would limit it only to root tasks, so that we have clearly separated blocks 

- It would be amazing to be able to **expand and collapse** tasks, at least the root ones. Readability of what you need to get done would improve sooo much :) 

- For the future, something that I'd really like would be some sort of "focus mode", in which you are able to hit the "focus" button on a task making everything else disappears: no sidebars, no header... Only the task details, sub-tasks and notes nicely laid out :pray:

**Comment by raimund-schluessler** [comment]
> - It would be amazing to be able to **expand and collapse** tasks, at least the root ones. Readability of what you need to get done would improve sooo much :) 

@ma12-co This is possible already. You can click "Hide subtasks" in the dropdown menu and all subtasks will be hidden:

Subtasks shown:
<img width="809" alt="shown" src="https://user-images.githubusercontent.com/2496460/87514685-e8119e80-c67a-11ea-86a5-792986073dcf.png">

Subtasks hidden:
<img width="804" alt="hidden" src="https://user-images.githubusercontent.com/2496460/87514697-ecd65280-c67a-11ea-9d0b-d790b2c10f92.png">

This works for every task, also subtasks.

**Comment by raimund-schluessler** [comment]
> - I think that the idea of separation mentioned [here](https://github.com/nextcloud/tasks/issues/664#issuecomment-656903971) is really nice, but I would limit it only to root tasks, so that we have clearly separated main blocks;

I am not sure about the separation. I think this would look weird if you have a lot of tasks without subtasks. I would not introduce that by default and refer to the custom CSS app since it is a small change.

**Comment by ma12-co** [comment]
> @ma12-co This is possible already. You can click "Hide subtasks" in the dropdown menu and all subtasks will be hidden

Oh, I didn't notice it! @raimund-schluessler, don't you think it would be better to show an icon on the left of the checkbox? Like: 
`> [] My task` for a collapsed task that has subtasks 
`[] My task` for a task that doesn't have subtasks 
Atm I don't see any distinction between the two

**Comment by raimund-schluessler** [comment]
We show an icon on the right side, left of the dropdown menu (see the second image). If we want to show an icon at the left we would need to shift the checkbox which would leave unused space if no icon is shown. I guess we would need a mockup to judge if that would work.

**Comment by ma12-co** [comment]
> I think this would look weird if you have a lot of tasks without sub-tasks

Not if the gap is small enough imo, like 4 to 8 px. Currently If you have a lot of tasks with sub-tasks it there's very little hierarchy and it all looks like the same slab.

**Comment by ma12-co** [comment]
> If we want to show an icon at the left we would need to shift the checkbox which would leave unused space if no icon is shown.
 
no problem with the checkbox shift imo, it's yet another clue that suggests you that there's something different about that particular task :)

**Comment by timkrief** [comment]
In my humble opinion, the checkbox should be the first thing to be seen, followed by the name of the task. Simple todo lists have to look clean too. If you really wanted to, you could display the number of subtasks and an option to show/hide them as a label, as it is done in tasks.org
![image](https://user-images.githubusercontent.com/14089949/87553620-6c801380-c6b3-11ea-81e7-e3ec510224ed.png)

**Comment by ma12-co** [comment]
To be honest those variable height elements with labels all around do not look very tidy to me. I think my proposal would still look cleaner.

**Comment by raimund-schluessler** [comment]
I would like to keep the checkbox on the very left. In my opinion it is the most important action element. Moving it to the right would be counterintuitive for me. And every other todo app I am aware of also has the checkbox to the very left. Breaking that custom for the add-subtask/show-subtask button is not reasonable for me, since these buttons are not so important.

However, I can understand that one would like to show it more prominently when a task has subtasks (which might be even hidden). But I would like to show that on the right side at the position where we already have the respective icon. We could maybe show the number of subtasks as a counter with a colored background (similar to how tasks.org apparently does it, but in a single line).

**Comment by ma12-co** [comment]
Ok, so how about putting the arrow on the far right of the task element? 

![Group 5](https://user-images.githubusercontent.com/26852655/87650308-bae3ef80-c751-11ea-9a2d-696954cd14b7.png)

**Comment by timkrief** [comment]
Yeah I don't like multiple lines at all either. I think they do that because of the size of mobile displays. but I like that the number of subtasks is displayed and that it is shown the same way as a label. As if the fact that it has subtasks put it in a "has subtasks" category 🙂

I really think the checkbox should be the only thing on the right personnally.

**Comment by timkrief** [comment]
I'm almost done editing the `style.scss` file to make my PR and I found out there's a `--border-radius` and a `--border-radius-large` as standard css variables. which one do you like the most?

`border-radius: var(--border-radius)`
![image](https://user-images.githubusercontent.com/14089949/87707855-12aa4700-c7a2-11ea-8e53-26939191c75d.png)

`border-radius: var(--border-radius-large)`
![image](https://user-images.githubusercontent.com/14089949/87707656-c52dda00-c7a1-11ea-8415-2d96e32c3cb8.png)

**Comment by szaimen** [comment]
I like the `border-radius: var(--border-radius-large)` more
But I am aware that it doesn't fit the overall Nextcloud Design so it probably will be `border-radius: var(--border-radius)` in the end.

**Comment by Bugsbane** [comment]
I agree that the gaps between deeper and shallower elements in my previous mockup looks weird (although less so than what came before).

That said, I feel that just removing *all* gaps, visually throws all tasks in together as one rather jumbled lump, reducing readability. Instead of either, what about if we only have a gap before a new root level task that has subtasks displayed above it? I didn't bother to mockup where the arrows/stars go:

![tasks](https://user-images.githubusercontent.com/401733/87883615-a6645900-c9d6-11ea-876a-93ba60f611a2.png)

There would be no gap between root tasks that had their subtasks collapsed:
![tasks2](https://user-images.githubusercontent.com/401733/87883750-7bc6d000-c9d7-11ea-85f2-2507fdba44e4.png)

**Comment by timkrief** [comment]
I find it weird that it would act differently for tasks with or without subtasks and on top of that for root tasks and deeper tasks. Plus it could create confusion for when tasks from all calendars are displayed as groups in the main view, as it would visually create multiple groups for one calendar. I think the indentation already provides the information we need to clearly comprehend the hierarchy and separations etc.

**Comment by ma12-co** [comment]
I don't think there's any problem if we have a 4px gap even when the tasks are collapsed or for when they don't have subtasks. @timkrief, the indentation might be enough for you as a programmer [but screenshot 1 of the previous comment](https://github.com/nextcloud/tasks/issues/664#issuecomment-660698956)  is unquestionably clearer to read for the average user and presents no significant drawbacks. That's why I think we should go for it.

**Comment by timkrief** [comment]
Okay so I'm testing with the dark theme, and it's looking pretty good imho
![image](https://user-images.githubusercontent.com/14089949/87935389-51394d80-ca91-11ea-98f6-904cd83f4e43.png)

**Comment by jancborchardt** [comment]
Just some meta input, since the issue has long veered off its original intention:
- Can this be split into smaller changes and/or pull requests? This way we don’t have one huge changeset where a tiny disagreement can block everything. E.g. the main discussion now is about the content list, and the sidebar is completely separate topic.
- With everyone putting in their thoughts on design, keep in mind who our competition is and what people are used to. That would be: [Microsoft To Do](https://www.microsoft.com/microsoft-365/microsoft-to-do-list-app), [Apple Reminders](https://support.apple.com/en-us/HT205890), [Google Tasks (which is integrated in Gmail)](https://play.google.com/store/apps/details?id=com.google.android.apps.tasks), [Todoist](https://todoist.com/), [Things](https://culturedcode.com/things/), [Any.do](https://www.any.do), and a to do list written on paper. We can learn a lot from their designs and the problems they solved, and the things they do or don’t show.

**Comment by raimund-schluessler** [comment]
I agree, for the PRs we should keep it small and start to include only the stuff where we have a consensus.

I will try to summarize a bit:

Where we have a consensus:
- The proposed changes to the task list from @timkrief should go into a PR. The task list will look like this for light mode
![image](https://user-images.githubusercontent.com/14089949/87707855-12aa4700-c7a2-11ea-8e53-26939191c75d.png)
 and dark mode
![image](https://user-images.githubusercontent.com/14089949/87935389-51394d80-ca91-11ea-98f6-904cd83f4e43.png)

Various opinions:
- There where proposals to separate different tasks (only when they have subtasks) by a 4 px gap, e.g. https://github.com/nextcloud/tasks/issues/664#issuecomment-660698956. I personally don't like that to much and since it's a simple change, I would refer to the custom CSS app for now.
- It should be better highlighted / shown if a task has hidden subtasks. We have the proposal to show an arrow on the right side when the subtasks are hidden or to adjust the current icon so that it is more prominent (e.g. by adding a counter of the hidden subtasks).

Since I have likely forgotten some ideas, I think it would be best to open separate issues for them.

@timkrief Could you please create a PR with the adjustments to the task list you proposed? And @jancborchardt please add @timkrief to the Tasks repo.

**Comment by raimund-schluessler** [comment]
Please have a look at https://github.com/nextcloud/tasks/pull/1136 for the task list style PR.
