### ISSUE TITLE
No list color and task progress

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/tasks#838]
### Steps to reproduce

1. Install the Task app.
2. Go to Task.
3. The "Tasks" list without color is automatically created.
4. Delete list.
5. Refresh the page.
6. A "Tasks" list is created again without a color assigned.
7. Create a new task.
8. Set the task completion percentage.

### Expected behaviour
Not creating tasks list automatically or creating a new tasks list with the assigned color.

### Actual behaviour

- A tasks list is created automatically without an assigned color.
- No progress visibility on the bar.

![obraz](https://user-images.githubusercontent.com/47037905/73257007-488f4b00-41c3-11ea-8112-0cdc5e549084.png)

![obraz](https://user-images.githubusercontent.com/47037905/73256965-31e8f400-41c3-11ea-8801-2ba8ee1b3849.png)

**Nextcloud version:** (see Nextcloud admin page)
17.0.2 and 18.0.0

**Tasks version:** (see Nextcloud apps page)
0.11.3

### Client configuration
**Browser:**
Firefox 17.0.2

**Operating system:**
Win7 and Win10

**Comment by raimund-schluessler** [comment]
I can confirm the issue. The problem is in this line https://github.com/nextcloud/tasks/blob/master/src/app.vue#L65

We have to specify a color there like here https://github.com/nextcloud/tasks/blob/master/src/components/TheList.vue#L400

Ref. for how Calendar choses the default color: https://github.com/nextcloud/calendar/blob/86530581909553914d746f49f553b0fe93c56132/src/views/Calendar.vue#L336

**Comment by raimund-schluessler** [comment]
We should also implement https://github.com/nextcloud/tasks/issues/835#issuecomment-579123623
