### ISSUE TITLE
Multiply the tasks when sharing with a group

### ISSUE THREAD

**Issue by jessenthiesen** [nextcloud/tasks#951]
### Steps to reproduce
1. Add a new task list
2. share the list with a group
3. "NEW" mark an option "Multiply the tasks when sharing with a group"

### Expected behaviour
Every single member of the group has the new task and can mark this task as completed by his own
### Actual behaviour
When a task is shared with a group and a single user mark the task as completed the task is completed for every user

I am teacher and want to give task to my students. When I share a list of tasks I want that every student do his work and mark the task as completed.

**Comment by raimund-schluessler** [comment]
While I understand the reasoning behind your feature request, this is a far to special use-case with a lot of open practical questions for which I don't see a good solution.
E.g. what happens if you unshare the list, would the students lose access to their list and progress? What happens when you edit a task / delete it / add one? Do they have to be multiplied again, do they vanish from the lists of your students? Would your edits overwrite the edits of your students? The expectations how such a feature should behave will most likely differ from user to user, which makes this feature basically unpredictable for most users. That's the most important reason, why I think it should not be implemented.

But, there is a quite simple alternative which exactly works as one would expect, and generates only minor overhead for your students:
You can export your task list as ICS file (just click "Download" in dropdown menu of the list) and share this file with your students. They can then import the ICS file (currently only in the Calendar app, but it will be visible in Tasks as well), chose if they want to import it into an exsiting calendar or create a new one, and everyone has their own private list.

As a side note, sharing a calendar / task list is a server feature, so this would need to be implemented in server, not in Tasks.
